chore: (QA) Integrate cypressOptions into cypress.config.cron.ts to test configuration path

diff --git a/.github/workflows/AlwaysData-cron.yml b/.github/workflows/AlwaysData-cron.yml
--- a/.github/workflows/AlwaysData-cron.yml
+++ b/.github/workflows/AlwaysData-cron.yml
@@ -25,15 +25,10 @@ jobs:
 
     - name: Check Necesary Secrets
       run: |
-        echo "ALWAYSDATA_USER=$ALWAYSDATA_USER"
-        echo "ALWAYSDATA_PASS=$ALWAYSDATA_PASS"
         if [ -z "$ALWAYSDATA_USER" ] || [ -z "$ALWAYSDATA_PASS" ]; then
           echo "Error: ALWAYSDATA_USER or ALWAYSDATA_PASS is not defined"
           exit 1
         fi
-
-    - name: List files in the working directory
-      run: ls -l
 
     - name: Cache Bun modules
       uses: actions/cache@v3
@@ -51,19 +46,19 @@ jobs:
     - name: Install dependencies
       run: bun install
 
-    - name: List files in cypress/Tests/utils
-      run: ls -l cypress/Tests/utils/
-
-    - name: Check Bun version
-      run: bun --version
-
-    - name: Install Chromium for Cypress
+    - name: Verify Cypress configuration and dependencies
       run: |
-        sudo apt-get update
-        sudo apt-get install -y chromium-browser
+        if ! test -f "cypress.config.cron.ts"; then
+          echo "Error: Cypress configuration file missing."
+          exit 1
+        fi
+        if ! bun list cypress; then
+          echo "Error: Cypress is not installed."
+          exit 1
+        fi
 
     - name: Run Alwaysdata Cron Job
       shell: bash
       run: |
         echo "ALWAYSDATA_USER=$ALWAYSDATA_USER"
-        bun run cypress run --browser chrome --headless --config-file=cypress.config.cron.ts --spec=cypress/Tests/utils/AlwaysData-cron.cy.ts
+        bun run cypress run --browser chrome --config-file=cypress.config.cron.ts --spec=cypress/Tests/utils/AlwaysData-cron.cy.ts
